### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by siyaofa** [Martazza/Huawei-Bootloader-Unlocker#10]
Thanks for your code, I want to try your method.

But I have not idea about how to Compile the source after searching in both Bing and Baidu.

The fact is that I don't know the Key Words for Pre-request Knowledge.

I have  experience in Both GCC and Android App Dev (Java).

So the question is:

1. What's the Tool for Compiling.
2. How to Run the Program we build.

I am appreciate if you add more details.

**Comment by Martazza** [comment]
I think your experience is not so deep..

Anyways...
`gcc source -o <out>`
This will compile the source and provides you a package with `out` name
Then run the compiled package...
