### ISSUE TITLE
FAILED (remote: invalid command)

### ISSUE THREAD

**Issue by chostarman** [Martazza/Huawei-Bootloader-Unlocker#2]
Is this normal, and if not, is there a fix?

**Comment by Martazza** [comment]
Yes... it's normal... it's a bruteforce attack. 
you need to wait: just a bit x)

**Comment by chostarman** [comment]
> Yes... it's normal... it's a bruteforce attack.
> you need to wait: just a bit x)

Roughly how long does it take?
