### ISSUE TITLE
huawei neo-l29

### ISSUE THREAD

**Issue by BeckeBauer** [Martazza/Huawei-Bootloader-Unlocker#3]
Does your tool also works with the huawei neo-l29 (2 IMEI numbers)?

**Comment by Martazza** [comment]
Yup

**Comment by BeckeBauer** [comment]
I tried but got the error message ```FAILED (remote: 'check password failed!')```
After 5th time, the error message is ```FAILED ('device will reboot after 30s due to 5 times of wrong key.')```
Any hint what to do (disable phone pw? - there is no sim pin set)?

**Comment by AkgunFatih** [comment]
@Martazza i have the same issue as @BeckeBauer

**Comment by Doping11** [comment]
> 
> 
> @Martazza i have the same issue as @BeckeBauer

Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.

**Comment by BeckeBauer** [comment]
@Doping11 code is not valid, but why would I want to reset the phone to factory settings?

**Comment by Doping11** [comment]
Dude it was too early for you, wasn´t it? I mean manufactor mod.

I didn´t talk about factory reset :-)

**Comment by BeckeBauer** [comment]
Maybe to early, but it still says invalid mmi code (to both codes)

**Comment by Doping11** [comment]
Ok. Last try: *#*#2846579#*#*

**Comment by Doping11** [comment]
When the menu pops up select "Project Menu", "Background settings", "USB ports settings" and then "Manufacture mode".

**Comment by AkgunFatih** [comment]
> > @Martazza i have the same issue as @BeckeBauer
> 
> Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.

nope doesnt work, on huwauie mate 10 lite

**Comment by Doping11** [comment]
> 
> 
> > > @Martazza i have the same issue as @BeckeBauer
> > 
> > 
> > Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.
> 
> nope doesnt work, on huwauie mate 10 lite

I have another one: *#*#2846579#*#*

It worked on my Honor 6X. Select "Project Menu", "Background settings", "USB ports settings", "Manufacture mode".

**Comment by AkgunFatih** [comment]
> > > > @Martazza i have the same issue as @BeckeBauer
> > > 
> > > 
> > > Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.
> > 
> > 
> > nope doesnt work, on huwauie mate 10 lite
> 
> I have another one: * # * # 2 8 4 6 5 7 9 # * # *
> 
> Try it without any "space".
> 
> It worked on my Honor 6X. Select "Project Menu", "Background settings", "USB ports settings", "Manufacture mode".

yea same for huwaie here but still FAILED (remote: 'check password failed!')

**Comment by Doping11** [comment]
> 
> 
> > > > > @Martazza i have the same issue as @BeckeBauer
> > > > 
> > > > 
> > > > Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.
> > > 
> > > 
> > > nope doesnt work, on huwauie mate 10 lite
> > 
> > 
> > I have another one: * # * # 2 8 4 6 5 7 9 # * # *
> > Try it without any "space".
> > It worked on my Honor 6X. Select "Project Menu", "Background settings", "USB ports settings", "Manufacture mode".
> 
> yea same for huwaie here but still FAILED (remote: 'check password failed!')

You receive the message "FAILED" because you have not yet found the correct unlock code.

**Comment by AkgunFatih** [comment]
> > > > > > @Martazza i have the same issue as @BeckeBauer
> > > > > 
> > > > > 
> > > > > Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.
> > > > 
> > > > 
> > > > nope doesnt work, on huwauie mate 10 lite
> > > 
> > > 
> > > I have another one: * # * # 2 8 4 6 5 7 9 # * # *
> > > Try it without any "space".
> > > It worked on my Honor 6X. Select "Project Menu", "Background settings", "USB ports settings", "Manufacture mode".
> > 
> > 
> > yea same for huwaie here but still FAILED (remote: 'check password failed!')
> 
> You receive the message "FAILED" because you have not yet found the correct unlock code.

how can i find it

**Comment by Doping11** [comment]
> 
> 
> I tried but got the error message `FAILED (remote: 'check password failed!')`
> After 5th time, the error message is `FAILED ('device will reboot after 30s due to 5 times of wrong key.')`
> Any hint what to do (disable phone pw? - there is no sim pin set)?

You should remove fingerprints, unlock pattern, google- and huawei account or device password.

The fastest way is to spend 4€ to get a unlock key. I did it and it worked fine for my Honor 6X.

That is the pay service: https://www.dc-unlocker.com/huawei-android-hisilicon-unlock-guide

**Comment by BeckeBauer** [comment]
@Doping11 the code * # * # 2 8 4 6 5 7 9 # * # * worked for me... I will try the unlock tool again after disabling fingerprint /password protection on the phone; 

by the way: did you get root access with the dc-unlocker tool? On their page it is said: '_WARNING: This network unlock does not unlock bootloader!_' (not sure if an unlocked boatloader is required for root access though)?

**Comment by AkgunFatih** [comment]
> @Doping11 the code * # * # 2 8 4 6 5 7 9 # * # * worked for me... I will try the unlock tool again after disabling fingerprint /password protection on the phone;
> 
> by the way: did you get root access with the dc-unlocker tool? On their page it is said: '_WARNING: This network unlock does not unlock bootloader!_' (not sure if an unlocked boatloader is required for root access though)?

don't buy from them it wont work
i had read somewhere on forum.xda-developers.com that its not working

**Comment by Doping11** [comment]
> 
> 
> @Doping11 the code * # * # 2 8 4 6 5 7 9 # * # * worked for me... I will try the unlock tool again after disabling fingerprint /password protection on the phone;
> 
> by the way: did you get root access with the dc-unlocker tool? On their page it is said: '_WARNING: This network unlock does not unlock bootloader!_' (not sure if an unlocked boatloader is required for root access though)?

You need to unlock the bootloader to get root. I bought the key there for 4€. But before buying, check the possibility on their website.

**Comment by Doping11** [comment]
Maybe you'll get lucky:
Multiply your IMEI by this factor 3,633366873662295. The Result might be your unlock code.

I have divided my unlock code by my IMEI. Lets try it. You can´t lose anything....

**Comment by AkgunFatih** [comment]
keep in mind that if you are using the latest android security patch
there is no way you can unlock your phone
says the guy from dc-unlocker
