### ISSUE TITLE
Huawie p10 lite remote: check password failed!

### ISSUE THREAD

**Issue by mujtaba765** [Martazza/Huawei-Bootloader-Unlocker#4]
when i run after complie i get "remote: check password failed!" 4 times and then (remote: device will reboot after 30S due to 5 times of wrong key.)  i have no fingerprint or password on device can you help please.
i have complied on windows using gcc commend from tdm64-gcc

**Comment by kko7** [comment]
It's an additional protection. You can't do anything about this 😢

**Comment by Djobi-Djoba** [comment]
Is there any way to automatically boot the phone always in fastboot mode without having to manually give the command "adb reboot bootloader"?

**Comment by kko7** [comment]
Press the Power button and the Volume Down button and hold them down for a few seconds.
or
Press and hold Volume Down button and connect the USB cable to your phone

**Comment by Djobi-Djoba** [comment]
Yes, that's what I already do, but every time the password fails and the phone automatically reboots normally not in fastboot mode. Is it possible to put the phone in a loop so that it always boots on fastboot mode?

**Comment by kko7** [comment]
There is probably some way, but I don't code in C, so I can't help you. Sorry

**Comment by Doping11** [comment]
Try to set your phone in manufactory mod: Type in dial ##2846579## and in background settings set manufactory mod.

**Comment by Kussh** [comment]
Even if you managed to make the program run it could take months of continuous processing to find your code.

**Comment by HappyDogy** [comment]
Hi brothers @Doping11 @Djobi-Djoba @kko7 @mujtaba765 @Kussh ,
How to run the .c object via fastboot command?
I also HUAWEI P10,  my phone not 'oem unlock 'check item  , and  passed all then stopped in step 7.
I search google but lose,  what should i do then?

**Comment by kko7** [comment]
You need to run the compiled .exe file after connecting the phone in bootloader mode to your computer.

https://www.wikihow.com/Compile-a-C-Program

**Comment by HappyDogy** [comment]
> 将电话以引导加载程序模式连接到计算机后，需要运行已编译的.exe文件。
> 
> [https://www.wikihow.com/Compile-aC-Program](https://www.wikihow.com/Compile-a-C-Program)

Oh, undersood, i must firest compile .c to .exe use my android studio and saved in computer, then use fastboot command?
Thank you kko7, im freshman :)

**Comment by Doping11** [comment]
> 
> 
> > 将电话以引导加载程序模式连接到计算机后，需要运行已编译的.exe文件。
> > [https://www.wikihow.com/Compile-aC-Program](https://www.wikihow.com/Compile-a-C-Program)
> 
> Oh, undersood, i must first compile .c to .exe use my android studio and saved in computer, then use fastboot command?
> Thank you kko7, im freshman :)

When you compiled the c-file then you have to use cmd-command-promt. Navigate in CMD to your generated .exe-file and just type the name of it in. Then press enter and the programm is running.

**Comment by HappyDogy** [comment]
> > > 将电话以引导加载程序模式连接到计算机后，需要运行已编译的.exe文件。
> > > [https://www.wikihow.com/Compile-aC-Program](https://www.wikihow.com/Compile-a-C-Program)
> > 
> > 
> > Oh, undersood, i must first compile .c to .exe use my android studio and saved in computer, then use fastboot command?
> > Thank you kko7, im freshman :)
> 
> When you compiled the c-file then you have to copy the .exe-file in your adb/fastboot-folder. I recommend to use "[minimal_adb_fastboot_1.4](https://androiddatahost.com/wp-content/uploads/minimal_adb_fastboot_v1.4.zip)" because in this version the fastboot-command is running faster then any other versions of fastboot (I tested it :-))
> After that you have to use cmd-command-promt. Navigate in CMD to your generated .exe-file and just type the name of it in. Then press enter and the program is running.
> 
> **I would first advise you to try this program https://github.com/SkyEmie/huawei-honor-unlock-bootloader**
> 
> When my recommended program reached the 17th digit you can cancel it.
> Afterwards you can try this unlocker with the c-file.

Well..... I tried and found that AndroidStudio may not compile. I try to browse CMAKE, but it may be more complicated for me. 
My current level is just learning the basic development of ANDROID  in CODELABS.
> You need to run the compiled .exe file after connecting the phone in bootloader mode to your computer.

I think I expanded here to a new knowledge structure (compiling C files and ADB command line). I first try to use " https://github.com/SkyEmie/huawei-honor-unlock-bootloader"
 I need to digest food, I will report the results here.

Have a nice day, my brothers. @Doping11  @kko7

**Comment by HappyDogy** [comment]
Hey bros, i come back .
I first tried use CMake compile .C to .exe , but i failed. and then , i download MINW-GCC tools on windows, its works. compiled .C to named 'a.exe', and i copy it to my platfrom-tools folder. 
adb restboot-bootloader ,then  fastboot flash PARTITION a.exe , then i get : 

Sending 'PARTITION' (45 KB)                        OKAY [  0.003s]
Writing 'PARTITION'                                FAILED (remote: 'Command not allowed')
fastboot: error: Command failed
Thats mean failed again?

@kko7  @Doping11 
![image](https://user-images.githubusercontent.com/49218866/82178841-8e595600-990f-11ea-87cc-a453f52d2741.png)

**Comment by Doping11** [comment]
> Hey bros, i come back .
> I first tried use CMake compile .C to .exe , but i failed. and then , i download MINW-GCC tools on windows, its works. compiled .C to named 'a.exe', and i copy it to my platfrom-tools folder.
> adb restboot-bootloader ,then fastboot flash PARTITION a.exe , then i get :
> 
> Sending 'PARTITION' (45 KB) OKAY [ 0.003s]
> Writing 'PARTITION' FAILED (remote: 'Command not allowed')
> fastboot: error: Command failed
> Thats mean failed again?
> 
> @kko7 @Doping11
> ![image](https://user-images.githubusercontent.com/49218866/82178841-8e595600-990f-11ea-87cc-a453f52d2741.png)

Does it mean that the SkyEmie-tool didn't work you?

I think i found your problem: Open cmd, navigate top your platform-tools-folder (your a.exe should be there) and start the program my using this command "a.exe". Then it starts. Now you can see  a lot of password fails (thats ok because you have both found the correct code already)

**Comment by HappyDogy** [comment]
> > Hey bros, i come back .
> > I first tried use CMake compile .C to .exe , but i failed. and then , i download MINW-GCC tools on windows, its works. compiled .C to named 'a.exe', and i copy it to my platfrom-tools folder.
> > adb restboot-bootloader ,then fastboot flash PARTITION a.exe , then i get :
> > Sending 'PARTITION' (45 KB) OKAY [ 0.003s]
> > Writing 'PARTITION' FAILED (remote: 'Command not allowed')
> > fastboot: error: Command failed
> > Thats mean failed again?
> > @kko7 @Doping11
> > ![image](https://user-images.githubusercontent.com/49218866/82178841-8e595600-990f-11ea-87cc-a453f52d2741.png)
> 
> Does it mean that the SkyEmie-tool didn't work for you?
> 
> I think i found your problem: Open cmd, navigate to your platform-tools-folder (your a.exe should be there) and start the program by using this command "a.exe". Then it starts. Now you can see a lot of password fails (thats ok because you have not found the correct code already)

Hi bro,
No, i from yestday start 'how to compile .c to exe on windows'and download tools until now, i seen skyEmie is bruteforce. so , i worried its will dominate phone

**Comment by kko7** [comment]
Both SkyEmie and Martazza tools are bruteforcing the unlock code, and none of them is trojan. SkyEmie is "based on the Luhn algorithm and the IMEI identifier used by the manufacturer to generate the unlocking code". You have to run a.exe from cmd after connecting phone to pc in bootloader mode

 [Make sure that you have enabled oem unlock in settings](https://fscl01.fonpit.de/userfiles/6473453/image/oem_unlocking.jpg)

**Comment by kko7** [comment]
Too late :/

**Comment by HappyDogy** [comment]
\

> Both SkyEmie and Martazza tools are bruteforcing the unlock code, and none of them is trojan. SkyEmie is "based on the Luhn algorithm and the IMEI identifier used by the manufacturer to generate the unlocking code". You have to run a.exe from cmd after connecting phone to pc in bootloader mode
> 
> [Make sure that you have enabled oem unlock in settings](https://fscl01.fonpit.de/userfiles/6473453/image/oem_unlocking.jpg)
> Too late :/

All right, im sad...

**Comment by kko7** [comment]
You could try dc-unlocker but I am not sure if it would work. You will have to google this. As far as I know it's not working on android 9 and above

**Comment by HappyDogy** [comment]
> You could try dc-unlocker but I am not sure if it would work. You will have to google this. As far as I know it's not working on android 9 and above

MY builder number is 8.0.0.046(0LU3)
I dont want pay for it. i just want try unlock by self

**Comment by kko7** [comment]
Send me dm on discord kko7#5194 or email j4kub.kko7@gmail.com I willtry to help you

**Comment by HappyDogy** [comment]
> Send me dm on discord kko7#5194 or email [j4kub.kko7@gmail.com](mailto:j4kub.kko7@gmail.com) I willtry to help you

Thank you brother, 
i send email . 
btw, i find this doc, https://source.android.com/setup/build/gsi#flashing-gsis, is it useful ?for fast oem unlock

**Comment by HappyDogy** [comment]
> > Send me dm on discord kko7#5194 or email [j4kub.kko7@gmail.com](mailto:j4kub.kko7@gmail.com) I willtry to help you
> 
> Thank you brother,
> i send email .
> btw, i find this doc,https://source.android.com/setup/build/gsi#flashing-gsis and https://source.android.com/setup/build/gsi#flashing-gsis, is it useful ?for fast oem unlock
