### ISSUE TITLE
hm

### ISSUE THREAD

**Issue by lubagov** [Martazza/Huawei-Bootloader-Unlocker#5]
At leas once it was finished? I try it with my phone, it work about 5 codes per second, for test all range, i need about 63 million years.

**Comment by amrithmmh** [comment]
yes i am wondering without he actual algorithm we wont be able to get the unlock code. but how does these unlock services as well as the DC huawei unlock bootloader work. i am sure they have the algorith.

**Comment by Doping11** [comment]
I found a way to improve the speed. Just use the compiled (generated .exe-) file with the "fastboot.exe" of "minimal adb fastboot 1.4 - version" (size: 783 KB).

Results:

V1.4.3 fastboot.exe: 1162 Calculations in 60 seconds.
V1.4.0. fasboot.exe: 1896 Calculations in 60 seconds.

**Comment by amrithmmh** [comment]
@Doping11 did you manage to get the code successfully?

**Comment by Doping11** [comment]
It is still running. It takes a while (maybe months).

**Comment by lubagov** [comment]
I get code, from other tool, for mybtablet, (US country, KOB-W09 Huawei MediaPad T3 8) it contains cany alhanumeric symbols.

**Comment by Doping11** [comment]
> 
> 
> I get code, from other tool, for mybtablet, (US country, KOB-W09 Huawei MediaPad T3 8) it contains any alhanumeric symbols.

Did you use a paid solution? Which one was it?

**Comment by lubagov** [comment]
Yes

**Comment by lubagov** [comment]
Codes for Chinese regione phones is numeric. Phor tablet for diffirent countyes it contain all alphabete

**Comment by YijunYuan** [comment]
> Codes for Chinese regione phones is numeric. Phor tablet for diffirent countyes it contain all alphabete

So this program only "works" for Chinese region phones?

**Comment by MudB0x** [comment]
> I get code, from other tool, for mybtablet, (US country, KOB-W09 Huawei MediaPad T3 8) it contains any alphanumeric symbols. Co it can contain letters

Could you tell me that tool name? I also have a  KOB-W09

**Comment by SkyEmie** [comment]
Hi, I could only test on European models (as indicated in the readme) and yep, the bootloaders of others regions are different, and I have no idea how the ones in the other regions work

**Comment by lubagov** [comment]
> > I get code, from other tool, for mybtablet, (US country, KOB-W09 Huawei MediaPad T3 8) it contains any alphanumeric symbols. Co it can contain letters
> 
> Could you tell me that tool name? I also have a KOB-W09

DC Phoenix/DC Unlocker
